version: 2

models:
  - name: stg_daily_ohlcv
    tests:
      - dbt_utils.unique_combination_of_columns:
          arguments:
            combination_of_columns: [symbol_id, trade_date]
    columns:
      - name: symbol_id
        tests:
          - not_null
          - relationships:
              arguments:
                to: ref('stg_symbols')
                field: symbol_id
      - name: trade_date
        tests: [not_null]

  - name: stg_symbols
    columns:
      - name: symbol_id
        tests: [not_null, unique]
      - name: ticker
        tests: [not_null, unique]
      - name: sector
        tests: [not_null]
